# Generated by Django 3.1.5 on 2021-01-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, to='cms.Category'),
        ),
    ]
