# Generated by Django 3.1.5 on 2021-01-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20210126_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seen',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
