# Generated by Django 3.1.5 on 2021-01-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_blog_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='seen',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
