# Generated by Django 3.1.5 on 2021-01-29 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20210127_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwsrest',
            name='datatime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
