# Generated by Django 3.1.5 on 2021-02-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20210201_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
