# Generated by Django 3.1.5 on 2021-02-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
