# Generated by Django 3.1.5 on 2021-02-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20210202_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='User/default.png', max_length=200, null=True, upload_to='User/'),
        ),
    ]
