# Generated by Django 3.1.5 on 2021-02-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_commentblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentblog',
            name='blog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.blog'),
        ),
    ]
