# Generated by Django 3.1.5 on 2021-02-07 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0023_auto_20210207_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentblog',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
