# Generated by Django 3.1.5 on 2021-02-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20210208_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='uuid',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
