# Generated by Django 3.1.5 on 2021-02-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_commentblog_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='uuid',
        ),
    ]
