# Generated by Django 3.1.5 on 2021-02-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_ticketmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ticketmain',
            name='answer',
            field=models.ManyToManyField(blank=True, related_name='answer_ticket', to='cms.TicketAnswer'),
        ),
        migrations.AddField(
            model_name='ticketmain',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='messages_ticket', to='cms.TicketSend'),
        ),
    ]
