# Generated by Django 3.1.6 on 2021-02-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_auto_20210209_1025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='staticdir',
        ),
    ]
