# Generated by Django 3.1.6 on 2021-02-09 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_auto_20210208_1956'),
        ('cms', '0031_delete_staticdir'),
    ]

    operations = [
    ]
