# Generated by Django 3.1.6 on 2021-02-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_auto_20210209_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='chanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
                ('createor', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('vazit', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'chanel',
                'verbose_name_plural': 'chanels',
            },
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=250)),
                ('mozoee', models.CharField(max_length=250)),
                ('des', models.TextField()),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.chanel')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
            },
        ),
    ]
