# Generated by Django 3.1.6 on 2021-02-09 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0034_chanel_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='createor',
        ),
        migrations.AddField(
            model_name='chanel',
            name='createor',
            field=models.ManyToManyField(related_name='createor', to=settings.AUTH_USER_MODEL),
        ),
    ]
