# Generated by Django 3.1.5 on 2021-02-09 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20210209_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanel',
            name='token',
            field=models.UUIDField(unique=True),
        ),
        migrations.CreateModel(
            name='ShortlinkBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shotrlink', models.CharField(max_length=10)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.blog')),
            ],
        ),
    ]
