# Generated by Django 3.1.6 on 2021-02-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_auto_20210209_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='token',
            field=models.UUIDField(unique=True),
        ),
    ]
