# Generated by Django 3.1.6 on 2021-02-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20210209_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='title2',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
