# Generated by Django 3.1.5 on 2021-02-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20210209_2127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortlinkBlog',
        ),
    ]
