# Generated by Django 3.1.5 on 2021-02-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_delete_shortlinkblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=20)),
                ('long', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
