# Generated by Django 3.1.5 on 2021-02-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0038_shorturls'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_link',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
