# Generated by Django 3.1.6 on 2021-02-10 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0039_auto_20210209_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 10, 8, 42, 27, 673462, tzinfo=utc)),
        ),
    ]
