# Generated by Django 3.1.5 on 2021-02-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0040_auto_20210209_2356'),
        ('cms', '0037_chanel_title2'),
    ]

    operations = [
    ]
