# Generated by Django 3.1.6 on 2021-02-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_auto_20210210_1213'),
        ('cms', '0041_merge_20210210_0007'),
    ]

    operations = [
    ]
