# Generated by Django 3.1.6 on 2021-03-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0042_merge_20210210_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=250, unique=True)),
                ('lastname', models.CharField(blank=True, max_length=150)),
                ('firstname', models.CharField(blank=True, max_length=150)),
                ('profile_img', models.ImageField(blank=True, upload_to='Users/Profile/')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('submit_email', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.AlterField(
            model_name='blog',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cms.user'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='like_star', to='cms.User'),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='createor',
            field=models.ManyToManyField(related_name='createor', to='cms.User'),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike_comment', to='cms.User'),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_comment', to='cms.User'),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.user'),
        ),
    ]
