# Generated by Django 3.1.6 on 2021-03-03 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0044_auto_20210303_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwsrest',
            name='datatime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
