# Generated by Django 3.1.6 on 2021-03-03 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0045_auto_20210303_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pwsrest',
            old_name='datatime',
            new_name='date',
        ),
        migrations.AddField(
            model_name='pwsrest',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
