# Generated by Django 3.1.6 on 2021-03-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0046_auto_20210303_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwsrest',
            name='timerest',
        ),
    ]
