# Generated by Django 3.1.6 on 2021-03-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0047_remove_pwsrest_timerest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chanel',
            name='title2',
        ),
    ]
